# Change these first
owner: scpzh
repo: upptime-for-scpzh

sites:
  - name: SCP Miraheze CN Wiki
    url: https://scpfoundation.miraheze.org
    type: globalping
    location: Singapore
  - name: Cloudflare
    url: https://www.cloudflarestatus.com/api/v2/status.json
  - name: GitHub
    url: https://github.com
  - name: Wikidot
    url: https://www.wikidot.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-for-scpzh
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SCP Miraheze CN 状态页
  introTitle: "**SCP Miraheze CN Status Page** based on **Upptime**, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
